// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_3.Models;

#nullable disable

namespace Project_2.Migrations
{
    [DbContext(typeof(ContextDBS))]
    partial class ContextDBSModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_2.Models.products", b =>
                {
                    b.Property<int>("P_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("P_id"));

                    b.Property<DateTime?>("P_DateInsert")
                        .HasColumnType("datetime2");

                    b.Property<bool>("P_available")
                        .HasColumnType("bit");

                    b.Property<string>("P_category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("P_height")
                        .HasColumnType("float");

                    b.Property<string>("P_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("P_price")
                        .HasColumnType("int");

                    b.Property<double?>("P_weight")
                        .HasColumnType("float");

                    b.HasKey("P_id");

                    b.ToTable("productss");
                });

            modelBuilder.Entity("Project_3.Models.bascket", b =>
                {
                    b.Property<int>("B_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("B_id"));

                    b.Property<string>("B_category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("B_price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("B_id");

                    b.ToTable("basckets");
                });

            modelBuilder.Entity("Project_3.Models.users", b =>
                {
                    b.Property<int>("P_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("P_id"));

                    b.Property<string>("U_age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_family")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("P_id");

                    b.ToTable("userss");
                });
#pragma warning restore 612, 618
        }
    }
}
